var o = {
  GET_INITIAL_DATA: 'GET_INITIAL_DATA',
  GET_DECADE_DATA: 'GET_DECADE_DATA',
  GET_COUNTY_BREAKDOWN_DATA: 'GET_COUNTY_BREAKDOWN_DATA',
  GET_COUNTRY_BREAKDOWN_DATA: 'GET_COUNTRY_BREAKDOWN_DATA',

  request: {
    PENDING: 'PENDING',
    ERROR: 'ERROR',
    TIMEOUT: 'TIMEOUT'
  }
}

module.exports = o;